"""AHMED AUTO stock — single source for build_final.py (and ported to site/src/data/dealer.ts).
Every value is copied from the dealer's own post (see brief.md). Missing = None, never guessed."""

STOCK_DATE = "2026-09-27"
STOCK_DATE_FR = "27 septembre 2026"

STOCK = [
    {
        "id": "cupra-formentor", "make": "Cupra", "model": "Formentor", "version": "e-Hybrid",
        "year": "07-2023", "yearNum": 2023, "km": 100000, "fuel": "Essence hybride rechargeable", "energy": "phev",
        "gearbox": None, "cv": 8, "power": None, "colour": "Gris Nardo", "type": "SUV",
        "date": "2026-09-27", "source": "Facebook",
        "url": "https://www.facebook.com/permalink.php?story_fbid=pfbid0KZfzmsXycSkLRRH8sBXzqgKDrh9nrPUncPcmjJ2gRetqAEz4SkgBL8gkgmbVKAdvl&id=100064048541047",
        "extra": [("Jantes", "Alliage Design Bronze R19")],
        "options": ["Rappels bronze sur les jantes, le logo et les sorties d'échappement",
                    "Sièges baquets sport électriques à mémoire, cuir perforé, chauffants",
                    "Toit panoramique ouvrant", "Éclairage d'ambiance LED « Smart Ambient Light »",
                    "Cockpit digital configurable, écran tactile 12\", navigation 3D",
                    "Apple CarPlay & Android Auto sans fil", "Système audio premium",
                    "Caméra de recul, radars avant/arrière, Park Assist",
                    "Régulateur adaptatif (ACC), Lane Assist, angles morts, Front Assist",
                    "Accès et démarrage sans clé (Keyless Advanced)",
                    "Coffre électrique mains libres (Virtual Pedal)", "Recharge sans fil smartphone",
                    "Projecteurs Full LED"],
        "photos": 8,
    },
    {
        "id": "mercedes-glc300e-coupe", "make": "Mercedes-Benz", "model": "GLC 300e Coupé", "version": "4MATIC",
        "year": "09/2025", "yearNum": 2025, "km": 36000, "fuel": "Essence + électrique (hybride rechargeable)", "energy": "phev",
        "gearbox": "Automatique 9G-Tronic", "cv": 11, "power": None, "colour": None, "type": "SUV coupé",
        "date": "2026-09-27", "source": "Facebook",
        "url": "https://www.facebook.com/permalink.php?story_fbid=pfbid027A5z1Ggo9os6qDDawjV8YX85hVeg5f45UdQwefD4AVY1Atnu6d6U8hi3Zs2Rm9oZl&id=100064048541047",
        "extra": [("Transmission", "4MATIC"), ("Intérieur", "Cuir Nappa camel")],
        "options": ["Sièges électriques mémorisés, chauffants et massants", "Affichage tête haute (HUD)",
                    "Projecteurs Digital Light", "Toit panoramique ouvrant",
                    "Audio Burmester® 4D-Surround", "Éclairage d'ambiance multicolore",
                    "Boule d'attelage électrique",
                    "Pack Assistance Plus : régulateur adaptatif, maintien de voie, angles morts, freinage d'urgence",
                    "Caméras 540° avec Park Assist et détection de trafic arrière",
                    "MBUX, navigation premium avec réalité augmentée",
                    "Apple CarPlay / Android Auto", "Recharge sans fil smartphone"],
        "photos": 8,
    },
    {
        "id": "bmw-530e", "make": "BMW", "model": "530e", "version": "G30 LCI Restylée · Luxury Line",
        "year": "05-2023", "yearNum": 2023, "km": 59000, "fuel": "Essence hybride rechargeable", "energy": "phev",
        "gearbox": None, "cv": 10, "power": None, "colour": None, "type": "Berline",
        "date": "2026-09-25", "source": "Facebook",
        "url": "https://www.facebook.com/permalink.php?story_fbid=pfbid022G96iLNmPqg1kbXij5hymz7ggqMSi944q9MeBNG7CBHCM3UFNxEnA7FA5wGsR9zZl&id=100064048541047",
        "extra": [("Intérieur", "Cuir Dakota marron")],
        "options": ["Sièges électriques mémorisés et massants", "Tableau de bord Sensatec", "Coffre électrique",
                    "Affichage tête haute (HUD)",
                    "BMW Live Cockpit Navigation Pro (double écran 12,3\"), BMW OS 7.0",
                    "Apple CarPlay & Android Auto sans fil", "Éclairage d'ambiance", "Toit ouvrant",
                    "Projecteurs BMW Digital Light", "Caméra de recul, Park Assist avec Cross Traffic",
                    "Maintien de voie, angles morts, freinage d'urgence actif",
                    "Commande vocale, kit mains libres, recharge sans fil, Wi-Fi embarqué"],
        "photos": 7,
    },
    {
        "id": "mercedes-a250e", "make": "Mercedes-Benz", "model": "Classe A 250e", "version": "AMG-Line · Fin Série",
        "year": "12/2022", "yearNum": 2022, "km": 92000, "fuel": "Essence hybride rechargeable", "energy": "phev",
        "gearbox": None, "cv": 8, "power": None, "colour": None, "type": "Compacte",
        "date": "2026-09-11", "source": "Facebook",
        "url": "https://www.facebook.com/permalink.php?story_fbid=pfbid02Ya6VigLwMhrLhyVLCz4tbQWrQ3v3zcKv5KW6mHUCHbLEW3uJUPuRC6QJDR6uqiTcl&id=100064048541047",
        "extra": [("Finition", "Pack AMG-Line Premium Plus & Pack Night"), ("Jantes", "AMG R19")],
        "options": ["Sièges cuir + Alcantara, électriques, mémorisés et massants", "Boule d'attelage",
                    "Écran Superscreen MBUX, réalité augmentée", "Toit panoramique ouvrant",
                    "Éclairage d'ambiance 64 couleurs", "Audio 4D-Surround",
                    "Projecteurs Digital Light Multi-Beam", "Caméra 360°, Park Assist avec Cross Traffic",
                    "Pack Assistance à la conduite Plus", "Commande vocale « Hey Mercedes »",
                    "Coffre électrique, recharge sans fil, Wi-Fi embarqué"],
        "photos": 8,
    },
    {
        "id": "vw-tiguan-gte", "make": "Volkswagen", "model": "Tiguan R-Line GTE", "version": "Pack R-Line & Pack Night",
        "year": "09/2021", "yearNum": 2021, "km": 75000, "fuel": "1.4 TSI essence + électrique (hybride rechargeable)", "energy": "phev",
        "gearbox": None, "cv": 8, "power": "245 ch DIN cumulés", "colour": "Blanc Nacré", "type": "SUV",
        "date": "2026-09-07", "source": "Facebook",
        "url": "https://www.facebook.com/permalink.php?story_fbid=pfbid0319GWRVXNft1vbDQ1MSSYHpbRxVWpAgeBxK4Ncs4qc16G1LUBRP5thWCw4mLWg17Sl&id=100064048541047",
        "extra": [("Jantes", "Alliage R-Line")],
        "options": ["Vitres arrière surteintées, becquet R-Line", "Digital Cockpit Pro, écran tactile",
                    "Sièges baquets électriques à mémoire", "Volant sport cuir à méplat avec palettes",
                    "Climatisation bi-zone", "Démarrage sans clé (Keyless Go)",
                    "Éclairage d'ambiance multicolore", "Projecteurs IQ.LIGHT Matrix LED",
                    "Park Pilot avec caméra de recul et radars avant/arrière",
                    "Régulateur adaptatif (ACC), Lane Assist, freinage d'urgence",
                    "Apple CarPlay / Android Auto sans fil, recharge par induction"],
        "photos": 7,
    },
    {
        "id": "canam-outlander-max", "make": "Can-Am", "model": "Outlander MAX XT", "version": "Quad 1000cc · biplace",
        "year": "09/08/2026", "yearNum": 2026, "km": 0, "fuel": None, "energy": None,
        "gearbox": "Automatique CVT", "cv": None, "power": None, "colour": "Noir / Gris Nardo", "type": "Quad",
        "date": "2026-08-26", "source": "Facebook",
        "url": "https://www.facebook.com/permalink.php?story_fbid=pfbid02oyyoyWrG4iw9A7rJGLGHNnNXepRvhttFsbsP79D2QyPuSzGVZRFCrVUK4q8J4i5ml&id=100064048541047",
        "extra": [("Moteur", "Rotax 1000cc"), ("Transmission", "2x4 / 4x4, blocage auto du différentiel avant")],
        "options": ["Treuil Can-Am", "Pare-chocs avant XT", "Coffres rigides avant et arrière Can-Am",
                    "Jantes aluminium noires, pneus tout-terrain", "Siège passager surélevé (version MAX)",
                    "Direction assistée DPS 3 modes", "Frein moteur intelligent (iEB)",
                    "Écran numérique multifonctions", "Signature lumineuse Full LED", "Boule d'attelage"],
        "photos": 7,
    },
    {
        "id": "vw-golf-8", "make": "Volkswagen", "model": "Golf 8", "version": "Diesel",
        "year": "01-2022", "yearNum": 2022, "km": None, "fuel": "Diesel", "energy": "diesel",
        "gearbox": None, "cv": 6, "power": None, "colour": None, "type": "Compacte",
        "date": "2026-08-08", "source": "Instagram",
        "url": "https://www.instagram.com/p/Dbxo7Eajsmv/",
        "extra": [], "options": [],
        "photos": 8,
    },
]
